name: smartclock
description: "SmartClock"
publish_to: "none"
repository: "https://www.github.com/smartclock-app/Clock"
version: 1.0.16

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.4
  alexaquery_dart: ^4.0.1
  provider: ^6.1.2
  intl: ^0.20.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  dio: ^5.7.0
  sqlite3: ^2.4.7
  path: ^1.9.0
  logger: ^2.4.0
  connectivity_plus: ^6.1.0
  bonsoir: ^5.1.10
  sqlite3_flutter_libs: ^0.5.26
  html: ^0.15.5
  web_socket_channel: ^3.0.1
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  package_info_plus: ^8.1.3
  open_filex: ^4.6.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  will_it_run: ^1.0.4

platforms:
  android:
  linux:
  ios:
  macos:
  windows:

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-SemiBold.ttf
          weight: 600
    - family: WeatherIcons
      fonts:
        - asset: fonts/WeatherIcons.ttf
