name: smartclock
description: "SmartClock"
publish_to: "none"
repository: "https://www.github.com/smartclock-app/Clock"
version: 1.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.4
  alexaquery_dart: ^4.0.1
  provider: ^6.1.2
  intl: ^0.19.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  dio: ^5.7.0
  json_schema: ^5.2.0
  sqlite3: ^2.4.7
  path: ^1.9.0
  logger: ^2.4.0
  connectivity_plus: ^6.1.0
  bonsoir: ^5.1.10
  sqlite3_flutter_libs: ^0.5.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  linux:
  ios:
  macos:
  windows:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/display/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: WeatherIcons
      fonts:
        - asset: fonts/WeatherIcons.ttf
