name: "Build & Release"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Check if Tag Exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check_tag
        with:
          tag: v${{ steps.extract_version.outputs.VERSION }}

      - name: Fail if Tag Exists
        if: steps.check_tag.outputs.exists == 'true'
        run: |
          echo "::error title=SKIPPING-BUILD::Version Tag Exists"
          exit 1

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: "oracle"
          java-version: "20"

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build IPA
        run: flutter build ipa --no-codesign

      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios_build.tar.gz

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/ios_build.tar.gz"
          tag: v${{ steps.extract_version.outputs.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
